from typing import Dict, List

check_rev_rel: dict[str, str] = {
    'chemicalentity_phenotype': 'phenotype_chemicalentity',
    'chemicalentity_molecularfunction': 'molecularfunction_chemicalentity',
    'anatomy_disease': 'disease_anatomy',
    'disease_protein': 'protein_disease',
    'cellularcomponent_protein': 'protein_cellularcomponent',
    'phenotype_protein': 'protein_phenotype',
    'protein_mutation': 'mutation_protein',
    'tissue_chemicalentity': 'chemicalentity_tissue',
    'protein_chemicalentity': 'chemicalentity_protein',
    'biologicalprocess_protein': 'protein_biologicalprocess',
    'molecularfunction_gene': 'gene_molecularfunction',
    'pathway_chemicalentity': 'chemicalentity_pathway',
    'tissue_gene': 'gene_tissue',
    'mutation_chemicalentity': 'chemicalentity_mutation',
    'pathway_protein': 'protein_pathway',
    'protein_gene': 'gene_protein',
    'molecularfunction_protein': 'protein_molecularfunction',
    'biologicalprocess_molecularfunction': 'molecularfunction_biologicalprocess',
    'tissue_protein': 'protein_tissue',
    'chemicalentity_plantextract': 'plantextract_chemicalentity',
    'disease_plantextract': 'plantextract_disease',
    'cellularcomponent_pmid': 'pmid_cellularcomponent',
    'chemicalentity_pmid': 'pmid_chemicalentity',
    'disease_pmid': 'pmid_disease',
    'protein_pmid': 'pmid_protein',
    'tissue_pmid': 'pmid_tissue',
}


Ntype_split: dict[str, list[str]] = {
    'phenotype_chemicalentity': ['phenotype', 'chemicalentity'],
    'mutation_disease': ['mutation', 'disease'],
    'molecularfunction_chemicalentity': ['molecularfunction', 'chemicalentity'],
    'disease_anatomy': ['disease', 'anatomy'],
    'chemicalentity_disease': ['chemicalentity', 'disease'],
    'disease_disease': ['disease', 'disease'],
    'biologicalprocess_gene': ['biologicalprocess', 'gene'],
    'protein_protein': ['protein', 'protein'],
    'gene_phenotype': ['gene', 'phenotype'],
    'protein_disease': ['protein', 'disease'],
    'anatomy_gene': ['anatomy', 'gene'],
    'chemicalentity_biologicalprocess': ['chemicalentity', 'biologicalprocess'],
    'disease_gene': ['disease', 'gene'],
    'gene_cellularcomponent': ['gene', 'cellularcomponent'],
    'chemicalentity_chemicalentity': ['chemicalentity', 'chemicalentity'],
    'cellularcomponent_gene': ['cellularcomponent', 'gene'],
    'gene_disease': ['gene', 'disease'],
    'protein_cellularcomponent': ['protein', 'cellularcomponent'],
    'protein_phenotype': ['protein', 'phenotype'],
    'mutation_protein': ['mutation', 'protein'],
    'chemicalentity_gene': ['chemicalentity', 'gene'],
    'chemicalentity_tissue': ['chemicalentity', 'tissue'],
    'chemicalentity_protein': ['chemicalentity', 'protein'],
    'biologicalprocess_biologicalprocess': ['biologicalprocess', 'biologicalprocess'],
    'phenotype_phenotype': ['phenotype', 'phenotype'],
    'phenotype_gene': ['phenotype', 'gene'],
    # 'chemicalentity_inhibits_biologicalprocess': ['chemicalentity', 'biologicalprocess'],
    # 'gene_inhibits_biologicalprocess': ['gene', 'biologicalprocess'],
    'protein_biologicalprocess': ['protein', 'biologicalprocess'],
    # 'gene_promotes_biologicalprocess': ['gene', 'biologicalprocess'],
    'gene_molecularfunction': ['gene', 'molecularfunction'],
    'gene_pathway': ['gene', 'pathway'],
    'chemicalentity_pathway': ['chemicalentity', 'pathway'],
    'gene_tissue': ['gene', 'tissue'],
    'disease_phenotype': ['disease', 'phenotype'],
    'chemicalentity_mutation': ['chemicalentity', 'mutation'],
    'gene_anatomy': ['gene', 'anatomy'],
    'phenotype_disease': ['phenotype', 'disease'],
    'pathway_gene': ['pathway', 'gene'],
    'disease_chemicalentity': ['disease', 'chemicalentity'],
    'disease_mutation': ['disease', 'mutation'],
    'gene_chemicalentity': ['gene', 'chemicalentity'],
    'protein_pathway': ['protein', 'pathway'],
    'gene_protein': ['gene', 'protein'],
    # 'gene_noeffect_biologicalprocess': ['gene', 'biologicalprocess'],
    # 'chemicalentity_promotes_biologicalprocess': ['chemicalentity', 'biologicalprocess'],
    'gene_biologicalprocess': ['gene', 'biologicalprocess'],
    'protein_molecularfunction': ['protein', 'molecularfunction'],
    'mutation_gene': ['mutation', 'gene'],
    'gene_gene': ['gene', 'gene'],
    'molecularfunction_molecularfunction': ['molecularfunction', 'molecularfunction'],
    'gene_mutation': ['gene', 'mutation'],
    'molecularfunction_biologicalprocess': ['molecularfunction', 'biologicalprocess'],
    'protein_tissue': ['protein', 'tissue'],
    'cellularcomponent_cellularcomponent': ['cellularcomponent', 'cellularcomponent'],
    'pathway_pathway': ['pathway', 'pathway'],
    'anatomy_anatomy': ['anatomy', 'anatomy'],
    'biologicalprocess_chemicalentity': ['biologicalprocess', 'chemicalentity'],
    'plantextract_chemicalentity': ['plantextract', 'chemicalentity'],
    'plantextract_disease': ['plantextract', 'disease'],
    'pmid_cellularcomponent': ['pmid', 'cellularcomponent'],
    'pmid_chemicalentity': ['pmid', 'chemicalentity'],
    'pmid_disease': ['pmid', 'disease'],
    'pmid_protein': ['pmid', 'protein'],
    'pmid_tissue': ['pmid', 'tissue'],
    # 'species_associatedwith_nodes': ['species', 'nodes'],
}
